services:
  app:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
    - ./database.db:/app/database.db

    environment:
      DB_CONNECTION: ${DB_CONNECTION:-sqlite}
      ENV: ${ENV:-production}
      API_KEYS_OPENWEATHER: ${API_KEYS_OPENWEATHER}
      DB_URL: ${DB_URL:-file:/app/database.db?mode=rwc&cache=shared&_fk=1}
      HTTP_ADDR: ${HTTP_ADDR:-:}${PORT:-8080}
      RUN_DAEMON: ${RUN_DAEMON:-false}
      OPENWEATHER_URL: ${OPENWEATHER_URL:-https://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&appid=%s&units=metric}