// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"us-soccer-go-test/internal/ent/predicate"
	"us-soccer-go-test/internal/ent/stadium"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StadiumDelete is the builder for deleting a Stadium entity.
type StadiumDelete struct {
	config
	hooks    []Hook
	mutation *StadiumMutation
}

// Where appends a list predicates to the StadiumDelete builder.
func (sd *StadiumDelete) Where(ps ...predicate.Stadium) *StadiumDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *StadiumDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *StadiumDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *StadiumDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(stadium.Table, sqlgraph.NewFieldSpec(stadium.FieldID, field.TypeUUID))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// StadiumDeleteOne is the builder for deleting a single Stadium entity.
type StadiumDeleteOne struct {
	sd *StadiumDelete
}

// Where appends a list predicates to the StadiumDelete builder.
func (sdo *StadiumDeleteOne) Where(ps ...predicate.Stadium) *StadiumDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *StadiumDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stadium.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *StadiumDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
