// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Stadium is the predicate function for stadium builders.
type Stadium func(*sql.Selector)

// Weather is the predicate function for weather builders.
type Weather func(*sql.Selector)
